### ISSUE TITLE
Remove threatening copy

### ISSUE THREAD

**Issue by aw** [erdg/picolisp-website#1]
The UI looks great! :sparkles: 

I don't believe PicoLisp should threaten potential new users though. At the end of the page, **Dangerous** seems quite harsh for a programming language. Is it a virus?

I can perhaps suggest **Challenging**, which is a bit friendlier.

I would also remove **You've been warned**. I don't think that's appropriate copy for the PicoLisp website.

**Comment by erdg** [comment]
Thanks!

Valid points, it was not my intention to threaten. I've changed it in the latest commit. I'd love any further suggestions regarding the copy! I'm not sold on it myself yet, just needed to get something down at that point.
